pipeline {
    agent none

    stages {
        stage("Build and test") {
            parallel {
                stage("Build and test CUDA platform") {
                    agent {
                        dockerfile {
                            filename "devtools/ci/jenkins/Dockerfile.gpu"
                            additionalBuildArgs '--build-arg GROUP_ID=$(id -g) --build-arg USER_ID=$(id -u) --build-arg USER_NAME=$(id -un)'
                            label "cuda && docker"
                            args "--gpus all"
                        }
                    }
                    steps {
                        sh "devtools/ci/jenkins/install.sh"
                        sh "devtools/ci/jenkins/test.sh -R 'TestCuda' --parallel 2"
                    }
                }

                stage("Build and test OpenCL platform") {
                    agent {
                        dockerfile {
                            filename "devtools/ci/jenkins/Dockerfile.gpu"
                            additionalBuildArgs '--build-arg GROUP_ID=$(id -g) --build-arg USER_ID=$(id -u) --build-arg USER_NAME=$(id -un)'
                            label "cuda && docker"
                            args "--gpus all"
                        }
                    }
                    steps {
                        sh "devtools/ci/jenkins/install.sh"
                        sh "devtools/ci/jenkins/test.sh -R 'TestOpenCL' --parallel 2"
                    }
                }

                stage("Build/test CPU platforms") {
                    agent {
                        dockerfile {
                            filename "devtools/ci/jenkins/Dockerfile.cpu"
                            additionalBuildArgs '--build-arg GROUP_ID=$(id -g) --build-arg USER_ID=$(id -u) --build-arg USER_NAME=$(id -un)'
                            label "docker"
                        }
                    }
                    steps {
                        sh "devtools/ci/jenkins/install_and_test_cpu.sh"
                    }
                }
            }
        }
    }
}
