pipeline {
    agent none

    stages {
        stage("Build and test") {
            parallel {
//                stage("Build and test CUDA platform") {
//                    agent {
//                        docker {
//                            image "test-image:latest"
//                            label "cuda && docker"
//                            args '--gpus all'
//                            alwaysPull true
//                        }
//                    }
//                    steps {
//                        sh "git clean -fxd && git checkout ."
//                        sh "devtools/ci/jenkins/install.sh"
//                        sh "devtools/ci/jenkins/test.sh -R 'TestCuda' --parallel 2"
//                    }
//                }
//
//                stage("Build and test OpenCL platform") {
//                    agent {
//                        docker {
//                            image "test-image:latest"
//                            label "cuda && docker"
//                            args '--gpus all'
//                            alwaysPull true
//                        }
//                    }
//                    steps {
//                        sh "git clean -fxd && git checkout ."
//                        sh "devtools/ci/jenkins/install.sh"
//                        sh "devtools/ci/jenkins/test.sh -R 'TestOpenCL' --parallel 2"
//                    }
//                }

                stage("Build/test CPU platforms") {
                    agent {
                        dockerfile {
                            filename "devtools/Dockerfile"
                            label "docker"
                        }
                    }
                    steps {
                        sh "wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
                        sh "bash Miniforge3-$(uname)-$(uname -m).sh -b"
                        sh "devtools/ci/jenkins/install_and_test_cpu.sh"
                    }
                }
            }
        }
    }
}
